### ISSUE TITLE
 when will you release the full code?

### ISSUE THREAD

**Issue by zahgnxiao1992** [clinplayer/Point2Skeleton#1]
Hello, I am a student in Shanghai Tech University . I am very interested in your article and would like to refer to some content. Could you please tell me when you will release the full code. Thank you

**Comment by clinplayer** [comment]
Hi, hopefully, the full code will be available within 2 months, once the paper is accepted.

**Comment by LordLiang** [comment]
Hi, congratulations on your excellent job accepted by cvpr2021！Can you release the full code recently？I am interested in it. Thank you!

**Comment by clinplayer** [comment]
The code is updated. Thanks!
