### ISSUE TITLE
Which tool did you use to visualize qualitative results in your paper?

### ISSUE THREAD

**Issue by trung6** [clinplayer/Point2Skeleton#11]
Hi, thanks for great work!
I just wonder which tool you used to visualize qualitative results in your CVPR paper.

**Comment by clinplayer** [comment]
Hey, we simply use Meshlab.
In FileRW.py, we have a function named save_skel_mesh(v, f, e, path_f, path_e) that outputs two separate files for skeletal curves and skeletal surfaces. We load the two files together in Meshlab.

**Comment by trung6** [comment]
Thanks!
