### ISSUE TITLE
About Volume-based closure

### ISSUE THREAD

**Issue by AceSilent** [clinplayer/Point2Skeleton#15]
Hello, after training and testing, I haven't found the volume-based closure. Could you please tell me where this file is or what ELSE I need to do to get it?

**Comment by clinplayer** [comment]
Could you see if this can help?
https://github.com/clinplayer/Point2Skeleton/issues/12#issuecomment-1019687201

**Comment by AceSilent** [comment]
According to your idea, I have finished the work. Thank you very much for your help.
