### ISSUE TITLE
Question about evaluation details

### ISSUE THREAD

**Issue by congxin0920** [clinplayer/Point2Skeleton#16]
Hello, could you please provide the code and datasets details for evaluation? Thank you very much

**Comment by clinplayer** [comment]
We have provided the link to the dataset we use. 
To compute CD-recon and HD-recon, specifically, we first get the radius of each skeleton point, and use the formulation like Eq.4 in the paper to approximate the CD or HD error. You don't have to reconstruct the complete surface.
These distance functions are implemented in DistFunc.py.

**Comment by congxin0920** [comment]
Hello, I'm sorry to bother you again. I used the method you mentioned above to evaluate the pre-trained model you gave, but the effect is worse than that in your paper. Could you please elaborate on the evaluation method?
