### ISSUE TITLE
Watertight surface extraction (Fig.10 in the paper)

### ISSUE THREAD

**Issue by lodurality** [clinplayer/Point2Skeleton#21]
Hello! 

Thanks for releasing your code and data -- great work. I can't find in your code the part that does unsupervised watertight surface reconstruction from point clouds (Fig. 10). 

As I see, your test code outputs spheres (XX_sphere.obj) but not the watertight meshes itself. Would you kindly share this part of the code or point it out the repo in case I have missed it?

Thank you!

**Comment by clinplayer** [comment]
Hey, thanks for your interest. 
Could you please check if this can help? 
https://github.com/clinplayer/Point2Skeleton/issues/12#issuecomment-1019687201

For Fig. 10, we use dense sampling and virtual scanning to get surface points with normals. Once you get a dense point cloud with normals, you can effortlessly use any reconstruction methods (like Poisson) to recover a watertight surface.

If this can't help you figure it out, I will consider releasing a version of the implementation.

**Comment by lodurality** [comment]
Yes, this is very helpful. Commented code lines in the test.py was exactly what I needed.
