### ISSUE TITLE
Deprecation of torch._six.int_classes and suggested replacement

### ISSUE THREAD

**Issue by chaidosa** [clinplayer/Point2Skeleton#23]
Description: The import statement from torch._six import int_classes is currently deprecated. After investigating, it was found that the suggested replacement for this is **int_classes = (bool, int)**.
Steps to reproduce: <br/>
1. Attempt to import int_classes using from torch._six import int_classes <br/>
2. Observe the error.
Suggested Solution: Use **int_classes = (bool, int)** instead of importing **int_classes** from **torch._six**.

Expected Outcome: The code that previously used **from torch._six import int_classes** should be updated to use **int_classes = (bool, int)** to avoid the deprecation error.

Additional Information: This change was introduced in the newer release of PyTorch and can be found in the documentation.

**Comment by clinplayer** [comment]
It seems the issue is caused by the usage of a higher version of torch. Thanks for pointing it out.
