### ISSUE TITLE
How to show/displace the testing result files?

### ISSUE THREAD

**Issue by manphis** [clinplayer/Point2Skeleton#27]
I was able to generate 6 output files for each point cloud input file when executing test.py.
But how can I show or display the 6 output files (2 .off files and 4 .obj files)?

thanks

**Comment by clinplayer** [comment]
Hi, you can drag all the files to MeshLab together. The .off file is the input point cloud, the *_edge.obj is the skeletal lines, and the *_face.obj is the skeletal faces.
