### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by LANXIAODDD** [clinplayer/Point2Skeleton#30]
Hi author, 
I used my own dataset to train the data and the output in the log folder had better results for the skeleton points.

Unfortunately, when I test the data using the weights 'weights-skeletonpoint.pth' obtained from the training, I find the results are very bad.

**Comment by clinplayer** [comment]
This looks abnormal. How much training data do you use? Are the training data aligned? Could you please also check if the tested point clouds are consistently aligned with your training data (in bounding box scale and orientation)?

**Comment by LANXIAODDD** [comment]
There are 900 training samples. Tree structures are categorized as complex, medium and simple.，and the number of points per sample is probably around 5000-6000. But I don't think this has much impact casue their bounding box scale and orientation are the same.
Even when I go to test using the data from training, the results were bad.

**Comment by clinplayer** [comment]
Hi, I'm a little confused by your question. In the first comment, you said the training results were good, but now you said "test using the data from training, the results were bad."

**Comment by LANXIAODDD** [comment]
sorry，I should explain in more detail
'test using the data from training, the results were bad' means I selected a few data from the training dataset and tested them through weights-skeletonpoint.pth and the results were bad.
'' The training results were good' means the results obtained from  the log folder were good.

**Comment by clinplayer** [comment]
Are the weights named weights-skeletonpoint.pth downloaded from the link I provided, or trained and saved successfully on your own?
If the results in the log folder look good, there is no reason why the testing results using the same training data are bad. Could please check if you use the correct checkpoint?

**Comment by LANXIAODDD** [comment]
The weights were trained and saved on my data. 
I'm sorry. What's checkpoint? I mean how do I check it
